# Generated by Django 5.1.1 on 2024-09-18 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_solarenergydata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
