# Generated by Django 5.1.1 on 2024-09-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_todoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarenergydata',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
