# Generated by Django 5.1.1 on 2024-09-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_solarenergydata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarenergydata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
